source 'https://github.com/CocoaPods/Specs.git'

target 'DroiOAuthDemo' do
    
pod 'DroiOAuthSDK'
pod 'DroiCoreSDK'
post_install do |installer|
require './Pods/DroiCoreSDK/scripts/postInstall.rb'
DroiCoreParser.installParser()
end

end